language: java    
jdk:
  - openjdk7
cache:  
  directories:  
   - $HOME/.m2
dist: trusty   
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"   
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start   
script:    
  - cd src/de.van_porten.vrest.build
  - mvn install
  - cat /home/travis/build/mcdeck/visualrest/src/de.van_porten.vrest.tests.core/target/work/data/.metadata/.log
deploy:  
  skip_cleanup: true  
  provider: releases  
  api_key:   
   secure: TBD
  file: 
    - src/de.van_porten.vrest.p2-repository/target/updatesite.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-win32.win32.x86.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-win32.win32.x86_64.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-linux.gtk.x86.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-linux.gtk.x86_64.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-macosx.cocoa.x86.zip
    - src/de.van_porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-macosx.cocoa.x86_64.zip
  on:  
   tags: true
   # condition: "$TRAVIS_TAG =~ ^release.*$"

   
  



