sudo: false  
language: java    
jdk:
  - openjdk7
cache:  
  directories:  
   - $HOME/.m2
env:  
  global:  
    - DISPLAY=:99.0  
  before_install:  
   - sh -e /etc/init.d/xvfb start - sleep 10  
script:    
  - cd src/de.van-porten.vrest.build
  - mvn install
deploy:  
  skip_cleanup: true  
  provider: releases  
  api_key:   
   secure: TBD
  file: 
    - de.van-porten.vrest.p2-repository/target/updatesite.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-win32.win32.x86.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-win32.win32.x86_64.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-linux.gtk.x86.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-linux.gtk.x86_64.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-macosx.cocoa.x86.zip
    - de.van-porten.vrest.p2-repository/target/products/de.van_porten.vrest.product-macosx.cocoa.x86_64.zip
  on:  
   tags: true
   # condition: "$TRAVIS_TAG =~ ^release.*$"

   
  



